
package verautopdf;

import com.itextpdf.text.DocumentException;
import java.io.BufferedWriter;
import java.io.Console;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


public class VerautoPDFgenerator extends javax.swing.JFrame {
private String inputpath;
private String outputpath;
private String logopath;

    public VerautoPDFgenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Create PDF report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Open Input directory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Select Output Directory");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Select Logo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("create from sim cmd");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*generape pdf object here*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        filespresent fp = new filespresent();
        if (fp.checkforfile(inputpath)) {
            //System.out.println("all files present");
            NcAutQuaEnSi N = new NcAutQuaEnSi(inputpath,logopath);
            NcAutQuaFran N2=new NcAutQuaFran(inputpath,logopath);
            NcAutQuaBrCompl N3=new NcAutQuaBrCompl(inputpath,logopath);
            try {
                N.genrep(outputpath,"default");
                N2.genrep(outputpath,"default");
                N3.genrep(outputpath,"default");
            } catch (DocumentException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
            }


        }
        else{
            System.out.println("some files missing");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

/*open directory of source files*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Select directory to source all files
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.setDialogTitle("Input Directory");
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        if (f==null){}else{
        System.out.println("input is " + f.getAbsolutePath());
        inputpath=f.getAbsolutePath();
        //////////
       
        
        //////////
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
/*choose save directory*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Select output directory
        JFileChooser chooser2 = new JFileChooser();
        chooser2.setDialogTitle("Output Directory");
        chooser2.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser2.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser2.showOpenDialog(null);
        File f2 = chooser2.getSelectedFile();
        if (f2==null){}
        else{            
        System.out.println("Output path is " + f2.getAbsolutePath());
        outputpath=f2.getAbsolutePath();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
/*select logo to be inserted*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Select logo
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.setDialogTitle(" logo Input");
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        if (f==null){}else{
        System.out.println(" logo input is " + f.getAbsolutePath());
        logopath=f.getAbsolutePath();
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerautoPDFgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerautoPDFgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerautoPDFgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerautoPDFgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  //new VerautoPDFgenerator().setVisible(true);//disabled if no user interface is desired
            }
        });
        /*command print return*/
       System.out.println("generating pdf from verautopdf generator");
      filespresent fp =new filespresent();
      fp.checkcmdfile();//initialises inputpath_fp,outputpath_fp,logopath_fp,three variables that tell the system where are the input paths ,outputpaths etc,to generate the pdf files
      ////////generate pdfs
       if (fp.checkforfile(fp.inputpath_fp)) {
           
          
            //System.out.println("all files present");
            NcAutQuaEnSi N = new NcAutQuaEnSi(fp.inputpath_fp,fp.logopath_fp);
            NcAutQuaFran N2=new NcAutQuaFran(fp.inputpath_fp,fp.logopath_fp);
            NcAutQuaBrCompl N3=new NcAutQuaBrCompl(fp.inputpath_fp,fp.logopath_fp);
            try {
                //anglais=1, Fr=33, Br=55
                if(fp.Langue_fp.contains("1")){N.genrep(fp.outputpath_fp,fp.FileName_fp);}
                else if (fp.Langue_fp.contains("33")){N2.genrep(fp.outputpath_fp,fp.FileName_fp);}
                else if (fp.Langue_fp.contains("55")){N3.genrep(fp.outputpath_fp,fp.FileName_fp);}
                else{
                    N.genrep(fp.outputpath_fp,fp.FileName_fp);}
                    
                
                
            } catch (DocumentException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
                messagelog.mymessages.add("Output path is null DocumentException");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
                messagelog.mymessages.add("Output path is null,FileNotFoundException");
            } catch (IOException ex) {
                Logger.getLogger(VerautoPDFgenerator.class.getName()).log(Level.SEVERE, null, ex);
                messagelog.mymessages.add("Output path is null,IOException");
            }finally{
            
            }


        }
        else{
            System.out.println("some files missing");
        }
      ///////end of generating pdfs
      
       ////OUtput a log file of any message logged into messagelog.mymessages linked list
       messagelog.dumpmsg();
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
